services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: my_postgres

    environment:
      POSTGRES_USER: gempilot
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gempilot

    ports:
      - "5432:5432"

    volumes:
      - gempilot_pg_data:/var/lib/postgresql
      - ./docker/postgres/init-extensions.sql:/docker-entrypoint-initdb.d/01-extensions.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gempilot -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gempilot_pg_data: